config/routes.rb
Rails.application.routes.draw do
  root 'pages#one'
  get 'pages/one'
  post 'pages/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end
  def new
    Student.create(name: params[:name],email: params[:email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tallerpreparacion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <body>
    <h1>Juan Rogelio Sandoval</h1>
    <p>before yield</p>
    <%= yield %>
    <p>after yield</p>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
  </body>
</html>

app/views/pages/one.html.erb
<!DOCTYPE html>
<html>
<h1>HELLO</h1>
<p>Find me in app/views/pages/one.html.erb</p>

<form action="<%=pages_new_path%>" method="post">
    <p>
    Nombre: <input type="text" name="name"><br>
    email: <input type="text" name="email"><br>
    <input type="submit" value="Enviar"> <input type="reset">
  </p>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
</form>

</html>